lyr01=readGRDECL('lyr01.grdecl');
z1=lyr01.ZCORN;
nx=80;ny=240;nz=80;
h=0:nz-1;
%h=repmat(h,[2 1]);
%h=h(:)';
dz=repmat(h,[8*nx*ny 1]);
dz=dz(:)';
z=repmat(z1,[nz 1])+dz';
act=repmat(lyr01.ACTNUM,[nz 1]);
ug=lyr01;
ug.ZCORN=z;
ug.ACTNUM=act;
ug.cartDims(3)=nz;
save('ug','ug');
clear ug z z1 lyr01 h nx ny nz dz act ; 
uc=readGRDECL('gc.grdecl');
upc=processGRDECL(uc);
save('../mat/upc','upc');
clear uc upc;
