k=10.^(-2:2);
ndims=[82 168 4];nmin=[26 7 1];nwl=[43 78 4];nmax=[82 161 4];
nArr=struct('dims',ndims,'nmin',nmin,'nmax',nmax,'nwl',nwl);
g=processGRDECL(readGRDECL([projDir() 'GRID_LRG.GRDECL']));
gLRG = computeGeometry(g);
g=processGRDECL(readGRDECL([projDir() 'GRID_SML.GRDECL']));
gSML = computeGeometry(g);

genCs(k,gLRG,nArr,'LRG');
genCs(k,gLRG,nArr,'SML');
% cmd = ['rm ' projDir() 'INJPRS_*_*1.*'...
%    projDir() 'INJPRS_*_*2.*'...
%    projDir() 'INJPRS_*_*4.*'...
%    projDir() 'INJPRS_*_*5.*'];
% system(cmd);
close all;
csArr = {...
   %'INJPRS_LRG_NET_13' ...
   'INJPRS_LRG_NET_23' ...
   'INJPRS_LRG_NET_33' ...
   'INJPRS_LRG_NET_43' ...
   'INJPRS_LRG_NET_53' ...
   %'INJPRS_SML_NET_13' ...
   'INJPRS_SML_NET_23' ...
   'INJPRS_SML_NET_33' ...
   'INJPRS_SML_NET_43' ...
   'INJPRS_SML_NET_53'};
 % };
colArr = { 'b' 'g' 'y' 'r'  'b.' 'g.' 'y.' 'r.'};
pltInjPrs(gLRG,gSML,nArr,csArr,colArr);
%legend('small-0.1','small-1','small-10','small-100',...
 %  'large-0.1','large-1','large-10','large-100');